name: walter_conda_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bbmap
  - bcftools
  - bowtie2
  - bwa
  - cutadapt
  - fastqc
  - gatk
  - kraken2
  - lofreq
  - mummer
  - mykrobe
  - picard
  - sambamba
  - samtools
  - tabix
  - tb-profiler
  - trim-galore
